# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomamenity',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_amenities', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='hostel.roomamenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='room',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.room'),
        ),
        migrations.AddField(
            model_name='hostelvisitorlog',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_visitor_logs', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelvisitorlog',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff'),
        ),
    ]
