# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('hostel', '0002_initial'),
        ('organization', '0001_initial'),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelvisitorlog',
            name='student_visited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='hostelinventory',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='hostelinventory',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_inventory', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='hostel.hostel'),
        ),
        migrations.AddField(
            model_name='hostelfeestructure',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_fee_structures', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelfacility',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_attendance', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='hostelattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='institution',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hostel.room'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='students.student'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='assistant_warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_managed_hostels', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='hostel.hostelfacility'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to='hr.staff'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hostel', 'room_number')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelattendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hostelallocation',
            unique_together={('student', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='hostel',
            unique_together={('institution', 'name')},
        ),
    ]
