# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
    ]
