# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('teachers', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department that offers this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Subjects that must be completed before taking this one', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='section',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.class'),
        ),
        migrations.AddField(
            model_name='section',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='house',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='class',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('institution', 'academic_year', 'class_name', 'section', 'day', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('institution', 'class_name', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('institution', 'name')},
        ),
    ]
