# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0002_initial'),
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.examtype'),
        ),
        migrations.AddField(
            model_name='exam',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='examtype',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='examsubject',
            unique_together={('exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam_subject', 'student')},
        ),
    ]
