# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='smslog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.notificationtemplate'),
        ),
    ]
