# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='noticeaudience',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_details', to='communications.notice'),
        ),
        migrations.AddField(
            model_name='noticeaudience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='notice',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template to use for this notice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['institution', 'status'], name='communicati_institu_83b0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='smslog',
            index=models.Index(fields=['recipient_number', 'created_at'], name='communicati_recipie_1d8fa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('institution', 'name')},
        ),
        migrations.AddIndex(
            model_name='noticeaudience',
            index=models.Index(fields=['notice', 'read'], name='communicati_notice__c4931f_idx'),
        ),
        migrations.AddIndex(
            model_name='noticeaudience',
            index=models.Index(fields=['user', 'read'], name='communicati_user_id_db77c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticeaudience',
            unique_together={('notice', 'user')},
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['institution', 'is_published', 'publish_date'], name='communicati_institu_a354c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['publish_date', 'expiry_date'], name='communicati_publish_dd5ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['institution', 'status'], name='communicati_institu_a5155d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient_email', 'created_at'], name='communicati_recipie_a231e3_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['institution', 'status'], name='communicati_institu_1f02f3_idx'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['scheduled_for', 'status'], name='communicati_schedul_6b0b1a_idx'),
        ),
    ]
