# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0003_initial'),
        ('students', '0001_initial'),
        ('transportation', '0001_initial'),
        ('organization', '0001_initial'),
        ('academics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransport',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.route', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentmedicalinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentidentification',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identification', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.hostel', verbose_name='Hostel'),
        ),
        migrations.AddField(
            model_name='studenthostel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class', verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='studentaddress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='students.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.academicyear', verbose_name='Academic Year'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.class', verbose_name='Current Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organization.institution'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.section', verbose_name='Section'),
        ),
    ]
