# Generated by Django 4.2.7 on 2025-09-25 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
        ('students', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPortalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('AUTO', 'Auto')], default='LIGHT', max_length=20, verbose_name='Theme')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Language')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_portal_settings', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_portal_settings', to='organization.institution', verbose_name='Institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_settings', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Portal Settings',
                'verbose_name_plural': 'Student Portal Settings',
                'db_table': 'students_portal_settings',
            },
        ),
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Login Count')),
                ('widgets_config', models.JSONField(default=dict, verbose_name='Widgets Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_dashboards', to='organization.institution', verbose_name='Institution')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Dashboard',
                'verbose_name_plural': 'Student Dashboards',
                'db_table': 'students_dashboard',
            },
        ),
        migrations.CreateModel(
            name='StudentPortalNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('FEE', 'Fee'), ('ATTENDANCE', 'Attendance'), ('EXAM', 'Exam'), ('EVENT', 'Event'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20, verbose_name='Type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('action_url', models.URLField(blank=True, verbose_name='Action URL')),
                ('related_model', models.CharField(blank=True, max_length=50, verbose_name='Related Model')),
                ('related_id', models.UUIDField(blank=True, null=True, verbose_name='Related ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_portal_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_portal_notifications', to='organization.institution', verbose_name='Institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notifications', to='students.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Portal Notification',
                'verbose_name_plural': 'Student Portal Notifications',
                'db_table': 'students_portal_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_read'], name='students_po_student_f7ea9b_idx'), models.Index(fields=['created_at'], name='students_po_created_2b2578_idx')],
            },
        ),
    ]
