# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_initial'),
        ('payments', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='refund',
            name='online_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.onlinepayment'),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentgateway'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payments', to='finance.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together={('institution', 'gateway_name')},
        ),
    ]
