# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_initial'),
        ('academics', '0003_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='hrattendance',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='hrattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.staff'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='class_teacher_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='faculty_members', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='designation',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_designations', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='designation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('institution', 'employee_id')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('institution', 'staff', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('staff', 'leave_type', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='hrattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'code')},
        ),
    ]
