# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_type', models.CharField(choices=[('LMV', 'Light Motor Vehicle'), ('HMV', 'Heavy Motor Vehicle'), ('MC', 'Motorcycle'), ('OTH', 'Other')], default='LMV', max_length=20)),
                ('license_expiry', models.DateField()),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, help_text="Driver's photo", null=True, upload_to='drivers/photos/')),
                ('id_proof', models.ImageField(blank=True, help_text="Driver's ID proof photo", null=True, upload_to='drivers/id_proofs/')),
                ('license_photo', models.ImageField(blank=True, help_text="Driver's license photo", null=True, upload_to='drivers/license_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_driver',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('breakdown', 'Breakdown'), ('accident', 'Accident Repair')], max_length=20)),
                ('date', models.DateField()),
                ('odometer_reading', models.IntegerField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('garage', models.CharField(blank=True, max_length=200)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_reading', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_maintenance',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=200)),
                ('end_point', models.CharField(max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in km', max_digits=6)),
                ('estimated_time', models.DurationField(help_text='Estimated travel time')),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_route',
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('sequence', models.IntegerField()),
                ('pickup_time', models.TimeField()),
                ('drop_time', models.TimeField()),
            ],
            options={
                'db_table': 'transport_route_stop',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='StudentTransport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_student_transport',
            },
        ),
        migrations.CreateModel(
            name='TransportAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transport_assignment',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('van', 'Van'), ('car', 'Car'), ('minibus', 'Mini Bus')], max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], max_length=20)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('registration_expiry', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution')),
            ],
            options={
                'db_table': 'transport_vehicle',
            },
        ),
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('pickup_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('drop_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='present', max_length=10)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution')),
            ],
            options={
                'db_table': 'transport_attendance',
            },
        ),
    ]
