# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportattendance',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportattendance',
            name='student_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.studenttransport'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.driver'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.route'),
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='drop_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_students', to='transportation.routestop'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='pickup_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_students', to='transportation.routestop'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='studenttransport',
            name='transport_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.transportassignment'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transportation.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transportattendance',
            unique_together={('student_transport', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studenttransport',
            unique_together={('student', 'start_date')},
        ),
    ]
