# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(choices=[('phd', 'PhD'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField()),
                ('experience', models.IntegerField(default=0)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('organization_type', models.CharField(choices=[('institute', 'Institute'), ('school', 'School'), ('college', 'College'), ('university', 'University'), ('coaching', 'Coaching Center'), ('other', 'Other')], default='school', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts'), ('computer', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('social_science', 'Social Science'), ('physical_education', 'Physical Education'), ('languages', 'Languages'), ('other', 'Other')], max_length=50, null=True)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('headmaster', 'Headmaster'), ('headmistress', 'Headmistress'), ('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('tutor', 'Tutor'), ('visiting_faculty', 'Visiting Faculty'), ('guest_lecturer', 'Guest Lecturer'), ('other', 'Other')], default='teacher', max_length=50)),
                ('faculty_type', models.CharField(choices=[('regular', 'Regular'), ('visiting', 'Visiting'), ('guest', 'Guest'), ('contract', 'Contract'), ('part_time', 'Part Time')], default='regular', max_length=20)),
                ('teaching_grade_levels', models.CharField(blank=True, help_text='Grade levels taught (e.g., 9-12, Undergraduate, etc.)', max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_resumes/')),
                ('degree_certificates', models.FileField(blank=True, help_text='Upload degree certificates', null=True, upload_to='teacher_certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='academics.class')),
                ('department_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_members', to='teachers.teacher')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institution')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject')),
            ],
            options={
                'db_table': 'teachers_teacher',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'teachers_salary',
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'On Leave'), ('half_day', 'Half Day')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'db_table': 'teachers_attendance',
            },
        ),
    ]
