# Generated by Django 4.2.7 on 2025-09-25 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teachersalary',
            unique_together={('teacher', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('teacher', 'date')},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['organization_type'], name='teachers_te_organiz_9407da_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teachers_te_departm_3b845d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['designation'], name='teachers_te_designa_4baf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active'], name='teachers_te_is_acti_964ac2_idx'),
        ),
    ]
